/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExemplo1 = new javax.swing.JToggleButton();
        btnExer1 = new javax.swing.JToggleButton();
        btnExer2 = new javax.swing.JToggleButton();
        btnExer3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Introdução a Orientação a Objetos ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));

        btnExemplo1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnExemplo1.setForeground(new java.awt.Color(0, 102, 102));
        btnExemplo1.setText("Exemplo 1");
        btnExemplo1.setName("btnExemplo"); // NOI18N
        btnExemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExemplo1ActionPerformed(evt);
            }
        });

        btnExer1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExer1.setForeground(new java.awt.Color(0, 102, 102));
        btnExer1.setText("Exercicio 1");
        btnExer1.setName("btnExerc1"); // NOI18N
        btnExer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExer1ActionPerformed(evt);
            }
        });

        btnExer2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExer2.setForeground(new java.awt.Color(0, 102, 102));
        btnExer2.setText("Exercicio 2");
        btnExer2.setName("btnExerc2"); // NOI18N
        btnExer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExer2ActionPerformed(evt);
            }
        });

        btnExer3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExer3.setForeground(new java.awt.Color(0, 102, 102));
        btnExer3.setText("Exercicio 3");
        btnExer3.setName("btnExerc3"); // NOI18N
        btnExer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExer3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnExer1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExer2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExer3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnExemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExer1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExer2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExer3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExer3ActionPerformed
        // TODO add your handling code here:
        Exercicio3 janela = new Exercicio3(null,false);
        janela.setVisible(true);
    }//GEN-LAST:event_btnExer3ActionPerformed

    private void btnExemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExemplo1ActionPerformed
        // TODO add your handling code here:
        Exemplo1 janela = new Exemplo1(null,false);
        janela.setVisible(true);
    }//GEN-LAST:event_btnExemplo1ActionPerformed

    private void btnExer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExer1ActionPerformed
        // TODO add your handling code here:
        Exercicio1 janela = new Exercicio1(null,false);
        janela.setVisible(true);
    }//GEN-LAST:event_btnExer1ActionPerformed

    private void btnExer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExer2ActionPerformed
        // TODO add your handling code here:
        Exercicio2 janela = new Exercicio2(null,false);
        janela.setVisible(true);
    }//GEN-LAST:event_btnExer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExemplo1;
    private javax.swing.JToggleButton btnExer1;
    private javax.swing.JToggleButton btnExer2;
    private javax.swing.JToggleButton btnExer3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
